[project]
name = "comfyui_goat_nodes"
description = "Nodes to level up your workflows performance and streamline specific functions: Image Tiler, Image Untiler,, Get Side Length Of Image, Advanced Upscale Image (using Model), Image Crop, Image Stitch, Capped Int (Positive), Capped Float (Positive), Int Divide (Rounded), Fast Film Grain, Fast Color Match, Advanced Sharpen, Triple Prompt, Sampler Settings, Image Dimensinos, Embedding Selector"
version = "1.1.1"
license = {file = "LICENSE"}
dependencies = []

[project.urls]
Repository = ""
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "AconexOfficial"
DisplayName = "ComfyUI_GOAT_Nodes"
Icon = ""